version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    security-updates-only: true
    commit-message:
      prefix: "fix"
      include: "scope"