version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      minors-and-patches:
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "fix"
      include: "scope"